#!/bin/bash
#using a sliding window of 3 values, count the number of increases between successive sums
cnt=0
a=(0 0 0)
i=0
lc=0
chkposnum()
{
	case $1 in
		'' | *[!0123456789]*)
			printf '%s\n' "$0: $1: invalid digit" ; exit 1
	esac
}

if [[ ! $1 ]] ; then
	echo 'Source filename needed!'
	exit 1
fi
while IFS= read -r crt; do
	chkposnum $crt
	# we only have 3 elements, no need for another loop
	s0=$((a[0]+a[1]+a[2]))

	# replace array element and reset index if needed
	a[i++]=$crt
	if [[ $i -eq 3 ]] ; then i=0 ; fi

	# sum again
	s1=$((a[0]+a[1]+a[2]))
	((lc++))
	if [[ $lc -gt 3 ]] && [[ s1 -gt s0 ]] ; then ((cnt++)) ; fi
done < "$1"
echo Count=$cnt
