#!/bin/bash
#compute position from movements and aim
#values read from stdin

aim=0
hpos=0
depth=0

updpos()
{
	case $1 in
		'forward')
			((hpos+=$2))
			((depth+=aim*$2));;
		'up')
			((aim-=$2))
			;;
		'down')
			((aim+=$2))
			;;
		*)
			echo "Unknown command $a[0]"
			;;
	esac
}

while IFS= read -r crt; do
	updpos $crt
done
echo "Depth = $depth"
echo "H Pos = $hpos"
