#!/bin/bash
# fish population
fisharr=()
fishgrp=()

procfish()
{
	local t=${fisharr[$1]}
	if(( t != 0 )) ; then
		(( fisharr[$1]-- ))
	else
		(( fisharr[$1]=6 ))
		fisharr+=(8)
	fi
}

procgrp()
{
	local t=${fishgrp[0]};
	for (( i=0; i<8 ; i++ )) ; do
		(( fishgrp[i]=fishgrp[i+1] ))
	done
	(( fishgrp[8]=t ))
	(( fishgrp[6]+=t ))
}

grpinit()
{
	for (( i=0 ; i<9 ; i++ )) ; do
		fishgrp+=(0)
	done
	for crt in "${fisharr[@]}" ; do
		(( fishgrp[crt]++ ))
	done
}

IFS=, read -ra fisharr

grpinit
for (( i=0 ; i<9 ; i++ )) ; do
	echo "g[$i]=${fishgrp[$i]}"
done
rc=$1
while (( rc-- )) ; do
	echo "days remaining $rc"
	procgrp
done
for (( i=0 ; i<9 ; i++ )) ; do
	echo "g[$i]=${fishgrp[$i]}"
done
fc=0
for (( i=0 ; i<9 ; i++ )) ; do
	(( fc+=fishgrp[$i] ))
done
echo "No. of fish: $fc"

